### ISSUE TITLE
Invalid posData length

### ISSUE THREAD

**Issue by JoshuaEstes** [bitpay/wpmembership-plugin#4]
When sending the information to the BitPay the plugin adds more information to the posData than needed. The "hash" needs to be removed and validation needs to make a call to BitPay to receive the invoice and verify against that.

Steps to Reproduce:

* Install http://premium.wpmudev.org/project/membership/ and activate and enable
* Go through and setup the the membership plugin and configure one of the membership levels to have a price attached to it
* Install this BitPay plugin and enable
* Goto the the Payment Gateways for the membership plugin and update the settings with an API key
* Open up a new (prefer incognito mode with chrome) browser and register on the site, during checkout just click the button and the error can be reproduced.

**Comment by ionux** [comment]
Fixed in PR #6
