### ISSUE TITLE
bad links

### ISSUE THREAD

**Issue by philosodad** [bitpay/wpmembership-plugin#5]
So this is forked off of ionux/, rather than the other way around, which causes some issues. For example, the readme links to the ionux branch, which is 4 commits behind the master branch, probably not the version we want people to install. I would say this can't be verified until that specific issue with the readme has been fixed.

**Comment by martindale** [comment]
I'll contact GitHub support to invert the upstream relationship.  What further action needs to be taken on this?

**Comment by philosodad** [comment]
That's about it. I updated the readme so that should be fine.

**Comment by ionux** [comment]
Thanks, Eric!
